nohup ./runESA.sh ../scenarios/AA-competing-poly-paper/AA-competing-poly-2-5-14-8s/ &
nohup ./runESA.sh ../scenarios/AA-competing-poly-paper/AA-competing-poly-2-5-14-12s &
nohup ./runESA.sh ../scenarios/AA-competing-poly-paper/AA-competing-poly-2-5-14-16s/ &
nohup ./runESA.sh ../scenarios/AA-competing-poly-paper/AA-competing-poly-2-5-15-8s/ &
nohup ./runESA.sh ../scenarios/AA-competing-poly-paper/AA-competing-poly-2-5-15-12s/ &
nohup ./runESA.sh ../scenarios/AA-competing-poly-paper/AA-competing-poly-2-5-15-16s/ &
nohup ./runESA.sh ../scenarios/AA-competing-poly-paper/AA-competing-poly-2-5-16-8s/ &
nohup ./runESA.sh ../scenarios/AA-competing-poly-paper/AA-competing-poly-2-5-16-12s/ &
nohup ./runESA.sh ../scenarios/AA-competing-poly-paper/AA-competing-poly-2-5-16-16s/ &
